import LayoutHome from '@layouts/HomeLayout'
import HomeCanvas from '@modules/Home/HomeCanvas'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Tanimur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LayoutHome className="-mt-16">
        <HomeCanvas />
      </LayoutHome>

     
    </>
  )
}
