import SocialLink2 from '@components/icons/socialicon';
import LayoutHome from '@layouts/HomeLayout';
import HomeAboutMe from '@modules/Home/HomeAboutMe';
import HomeCanvas from '@modules/Home/HomeCanvas';
import HomeIntro from '@modules/Home/HomeIntro';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Tanim-Full-stack web developer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <LayoutHome className='-mt-16'>
        <HomeCanvas />
        <HomeIntro />
        <div className=' flex justify-center items-start mt-10 lg:-mt-16 '>
          <SocialLink2></SocialLink2>
        </div>
        <HomeAboutMe/>
      </LayoutHome>
    </>
  );
}
